services:
  app:
    image: 'passenger-service:latest'
    build:
      dockerfile: Dockerfile
    container_name: passengers_app
    depends_on:
      - db
    networks:
      - microservices-network
    ports:
      - "8081:8081"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  db:
    image: postgres:latest
    container_name: passenger_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - microservices-network
    ports:
      - "5434:5432"
    volumes:
      - /var/lib/docker/volumes/passengers-db:/var/lib/postgresql/data

networks:
  microservices-network:
    external: true