services:
  passenger-service:
    image: 'passenger-service:latest'
    build:
      dockerfile: Dockerfile
    depends_on:
      - passengerdb-service
    container_name: passenger-service
    networks:
      - microservices-network
    ports:
      - "8081:8080"
      - "5005:5005"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  passengerdb-service:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: passenger_db
    networks:
      - microservices-network
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/docker/volumes/passengers-db:/var/lib/postgresql/data

networks:
  microservices-network:
    name: microservices-network
    external: true